name: Scrape
on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  Perform-Fetch:
    outputs:
      LATEST_LINUX_VERSION: ${{ steps.fetch.outputs.latest_linux_version }}
      LATEST_WINDOWS_VERSION: ${{ steps.fetch.outputs.latest_windows_version }}
      TRIGGER_LINUX_STABLE_BUILD: ${{ steps.fetch.outputs.trigger_linux_stable_build }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Perform fetch
        id: fetch
        run: ./fetch.sh
        env:
          LINUX_PATH: linux
          WINDOWS_PATH: windows
          LINUX_MANIFEST_URL: ${{ secrets.LINUX_MANIFEST_URL }}
          WINDOWS_MANIFEST_URL: ${{ secrets.WINDOWS_MANIFEST_URL }}
      - name: Try commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Updated versions"
  Trigger-Stable-Builds:
    runs-on: ubuntu-latest
    needs: Perform-Fetch
    if: needs.Perform-Fetch.outputs.TRIGGER_LINUX_STABLE_BUILD == 'true'
    steps:
      - name: Get app token
        id: get_bot_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.BDS_APP_PEM }}
          APP_ID: ${{ secrets.BDS_APP_ID }}
      - name: Trigger OCI build workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.get_bot_token.outputs.app_token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'ScriptAPIOSS',
              repo: 'BDS-OCI',
              workflow_id: 'build.yml',
              ref: 'main',
              inputs: {
                BDS_VERSION: '${{needs.Perform-Fetch.outputs.LATEST_LINUX_VERSION}}',
                USE_LATEST_TAG: "true",
                USE_STABLE_TAG: "true",
                USE_PREVIEW_TAG: "false"
              }
            })
  Trigger-Preview-Builds:
    runs-on: ubuntu-latest
    needs: Perform-Fetch
    if: needs.Perform-Fetch.outputs.TRIGGER_LINUX_PREVIEW_BUILD == 'true'
    steps:
      - name: Get app token
        id: get_bot_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.BDS_APP_PEM }}
          APP_ID: ${{ secrets.BDS_APP_ID }}
      - name: Trigger OCI build workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.get_bot_token.outputs.app_token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'ScriptAPIOSS',
              repo: 'BDS-OCI',
              workflow_id: 'build.yml',
              ref: 'main',
              inputs: {
                BDS_VERSION: '${{needs.Perform-Fetch.outputs.LATEST_PREVIEW_VERSION}}',
                USE_LATEST_TAG: "false",
                USE_STABLE_TAG: "false",
                USE_PREVIEW_TAG: "true"
              }
            })
