name: Scrape
on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  Perform-Fetch:
    outputs:
      LATEST_LINUX_VERSION: ${{ steps.fetch.outputs.latest_linux_version }}
      LATEST_PREVIEW_VERSION: ${{ steps.fetch.outputs.latest_linux_preview_version }}
      LATEST_WINDOWS_VERSION: ${{ steps.fetch.outputs.latest_windows_version }}
      TRIGGER_LINUX_STABLE_BUILD: ${{ steps.fetch.outputs.trigger_linux_stable_build }}
      TRIGGER_LINUX_PREVIEW_BUILD: ${{ steps.fetch.outputs.trigger_linux_preview_build }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Perform fetch
        id: fetch
        run: ./fetch.sh
        env:
          LINUX_MANIFEST_URL: ${{ secrets.LINUX_MANIFEST_URL }}
          WINDOWS_MANIFEST_URL: ${{ secrets.WINDOWS_MANIFEST_URL }}
          LINUX_PREVIEW_MANIFEST_URL: ${{ secrets.LINUX_PREVIEW_MANIFEST_URL }}
          WINDOWS_PREVIEW_MANIFEST_URL: ${{ secrets.WINDOWS_PREVIEW_MANIFEST_URL }}
      - name: Try commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Updated versions"
