# .github/workflows/update-versions-and-readme.yml
name: Update Versions and README

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest versions.json
        run: |
          curl -s https://raw.githubusercontent.com/Bedrock-OSS/BDS-Versions/main/versions.json -o versions.json

      - name: Extract latest versions
        id: extract_versions
        run: |
          LINUX_STABLE=$(jq -r '.linux.stable' versions.json)
          LINUX_PREVIEW=$(jq -r '.linux.preview' versions.json)
          WINDOWS_STABLE=$(jq -r '.windows.stable' versions.json)
          WINDOWS_PREVIEW=$(jq -r '.windows.preview' versions.json)

          echo "LINUX_STABLE=$LINUX_STABLE" >> $GITHUB_ENV
          echo "LINUX_PREVIEW=$LINUX_PREVIEW" >> $GITHUB_ENV
          echo "WINDOWS_STABLE=$WINDOWS_STABLE" >> $GITHUB_ENV
          echo "WINDOWS_PREVIEW=$WINDOWS_PREVIEW" >> $GITHUB_ENV

      - name: Update README
        run: |
          chmod +x readme.sh
          ./readme.sh "$LINUX_STABLE" "$WINDOWS_STABLE" "$LINUX_PREVIEW" "$WINDOWS_PREVIEW"

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Update versions.json and README with latest BDS versions"
